sudo: true
language: rust
services:
  - postgresql
rust:
  - nightly
before_script:
  - psql -c 'create database blog;' -U postgres
script:
  - cargo install diesel_cli --no-default-features --features postgres
  - diesel migration run
  - cargo test --verbose --all
  - cargo build  --verbose --all
  # - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  # - docker build -t blog .
  # - docker images
  # - docker tag blog $DOCKER_USERNAME/blog
  # - docker push $DOCKER_USERNAME/blog
