[package]
authors = ["Samray <samrayleung@gmail.com>"]
name = "blog"
version = "0.1.0"

[dependencies]
diesel = { version = "0.14.0", features = ["postgres"] }
diesel_codegen = { version = "0.14.0", features = ["postgres"] }
dotenv = "0.9.0"
error-chain = "0.10.0"
r2d2 = "0.7.3"
r2d2-diesel = "0.14.0"
rocket = "0.3.0"
rocket_codegen = "0.3.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.rocket_contrib]
default-features = false
features = ["handlebars_templates", "tera_templates"]
version = "*"
