[package]
authors = ["Samray <samrayleung@gmail.com>"]
name = "blog"
version = "0.1.2"

[dependencies]
dotenv = "0.13.0"
error-chain = "0.12.0"
lazy_static = "1.1.0"
r2d2 = "0.8.3"
r2d2-diesel = "1.0.0"
rocket = "0.4.0"
rocket_codegen = "0.4.0"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
tera = "0.11.20"
rust-crypto = "0.2.36"
bcrypt = "0.2.1"
rand = "0.6.4"
# 确保和diesel的ipnetwork 版本一致, 用cargo tree 命令查看
ipnetwork = "0.12.8"

[dependencies.chrono]
features = ["serde", "rustc-serialize"]
version = "0.4.6"

[dependencies.diesel]
features = ["postgres", "chrono","network-address"]
version = "1.3.2"

[dependencies.rocket_contrib]
default-features = false
features = ["handlebars_templates", "tera_templates", "json"]
version = "0.4.0"
